version: "3.3"
#docker-compose run cloud_file_service_backend sh
#docker-compose run cloud_file_service_frontend sh
#docker-compose up --force-recreate
services:
  cloud_file_service_frontend:
    build:
      ./
    ports:
    - 8080:8080
    image: front_app:1.0
  cloud_file_service_backend:
    build:
      ./
    ports:
      - 8888:8888
    image: cloud_service_app:1.0
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/postgres
  postgres:
    build:
      ./
    image: postgres
    ports:
    - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres